1. What is a Python library? Why do we use Python libraries?

A python library is a collection of pre-written code and functions that can be reused by developers to perform common tasks. These libraries contain modules and packages that provide specific functinalities ,maj=king it easier for devlopers to implement complex operations without having to write the code from scratch.

>>python libraries serve several purpose:

1. Code Reusability:
                    libraries alloww developers to reuse existing code,saving time and effort. instead of writing code for common tasks, developers can simply imporrt a library and use its functions.
2. Modularity:
              Libraries are modular,meaning they are organized into modules or packages that focus on specific functionalities. This modularity
              enhances code organization and maintainability.

3. Efficiency:
               Libraries are typically optimized and well-tested, providing efficient and reliable solutions to common problems. This allows developers to benefit from the expertise of others without having to reinvent the wheel.

4. Community Contribution: 
                          Python has a large and active community of developers who contribute to the creation and improvement of libraries. This collaborative effort results in a wide range of high-quality libraries covering various domains.

5.Rapid Development:
                    Using libraries can significantly speed up the development process. Developers can leverage existing solutions to build applications faster, reducing development time and costs.

6.Cross-Platform Compatibility:
                             Many Python libraries are designed to be cross-platform, making it easier to write code that can run on different operating systems without modification.

Examples of popular Python libraries include NumPy for numerical computing, pandas for data manipulation and analysis, Matplotlib for data visualization, requests for handling HTTP requests, and TensorFlow for machine learning, among many others.

2. What is the difference between Numpy array and List?

NumPy arrays and Python lists are both used to store and manipulate collections of data, but they have several key differences:

1.Data Type:

      >      In a Python list, elements can be of different data types, and   you can have a mix of integers, floats, strings, etc.
      >      In a NumPy array, all elements must be of the same data type. This homogeneity allows for more efficient storage and operations on the data.
2.Performance:

      >      NumPy arrays are more efficient in terms of memory and performance compared to Python lists. NumPy is implemented in C and optimized for numerical operations, making it faster for large datasets and mathematical computations.
      >      Lists are more flexible but may be slower for numerical operations due to their dynamic typing and less optimized structure.

3.Functionality:

       >     NumPy provides a wide range of mathematical functions and operations that can be applied directly to arrays. These operations are vectorized, meaning they operate on entire arrays without the need for explicit looping.
        >    Lists have fewer built-in operations for mathematical operations, and performing operations on individual elements often requires explicit loops.
4.Syntax:

       >     NumPy arrays support a more concise and expressive syntax for mathematical operations. For example, you can perform element-wise addition on NumPy arrays directly, while with lists, you would need to use a loop or list comprehension.
       >   Lists are more general-purpose and have a simpler syntax for basic operations.

Here's a brief example illustrating some of these differences:
# Using Python lists
python_list = [1, 2, 3, 4]
python_list_squared = [x**2 for x in python_list]

# Using NumPy arrays
import numpy as np

numpy_array = np.array([1, 2, 3, 4])
numpy_array_squared = numpy_array**2

in this example, the NumPy array allows for a more concise and efficient way to perform element-wise squaring compared to the Python list.










3. Find the shape, size and dimension of the following array?


[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [1]:
import numpy as np 

#Given array
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

#shap of the array
shape = arr.shape

#Size of the array(total number of elements)
size = arr.size

#Dimension of the array
Dimension = arr.ndim

print("Shape:" , shape)
print("Size:",size)
print("Dimension:",Dimension)

Shape: (3, 4)
Size: 12
Dimension: 2


4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [4]:
import numpy as np

#Given array
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
# Access the first row
first_row  = arr[0,:]

print("First Row:",first_row)

First Row: [1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [5]:
import numpy as np

#Given array
arr= np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])

# Access the element at the third row and fourth column

element = arr[2,3]


print("Element at the third row and fourth column:",element)

Element at the third row and fourth column: 12


6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [6]:
import numpy as np

#Given array

arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

#Extract all odd-indexed elements

odd_indexed_elements = arr[:,1::2]

print(odd_indexed_elements)

[[ 2  4]
 [ 6  8]
 [10 12]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [7]:
import numpy as np
# Generate a random 3*3 matrix with values between 0 and 1

random_matrix = np.random.rand(3,3)

print("Random 3*3 matrix:")
print(random_matrix)

Random 3*3 matrix:
[[0.62821374 0.99714206 0.19363894]
 [0.60719718 0.21744158 0.99974401]
 [0.98989641 0.39740901 0.02154949]]


8. Describe the difference between np.random.rand and np.random.randn?

The NumPy functions np.random.rand and np.random.randn are both used to generate random numbers, but they differ in terms of the distribution of the generated values:

1.np.random.rand:

   > This function generates random values from a uniform distribution over the interval [0, 1).
   > The generated numbers are uniformly distributed between 0 (inclusive) and 1(exclusive).
   > The syntax is np.random.rand(d0, d1, ..., dn) where d0, d1, ..., dn are the dimensions of the output array.

Example:
import numpy as np

random_values = np.random.rand(2, 3)

2.np.random.randn:

    > This function generates random values from a standard normal distribution (mean=0, standard deviation=1).
    > The generated numbers are not uniformly distributed; instead, they follow a Gaussian distribution (bell-shaped curve).
    >  The syntax is np.random.randn(d0, d1, ..., dn) where d0, d1, ..., dn are the dimensions of the output array.

Example:
import numpy as np

random_values = np.random.randn(2, 3)



9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [14]:
import numpy as np
#Given array

arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

# Increase the dimension using np.expand_dims
expand_arr = np.expand_dims(arr,axis=2)

print("Original Array:")
print(arr)

print("\nArray with Increased Dimension:")
print(expand_arr)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array with Increased Dimension:
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [16]:
import numpy as np

#Given array
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

#transpose the array using numpy.transpose
transposed_arr_1 = np.transpose(arr)

#Transpose the array using the .T attribute
transposed_arr_2 = arr.T

print("Original Array:")
print(arr)

print("\nTranspose Array (using np.transpose):")
print(transposed_arr_1)

print("\nTranspose Array (using .T attribute):")
print(transposed_arr_2)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transpose Array (using np.transpose):
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Transpose Array (using .T attribute):
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python:

1.Index wise multiplication

2. Matrix multiplication

3. Add both the matrics

4. Subtact matrix B from a
 
5. Divide Matrix B by A

In [18]:
import numpy as np

#Given matrices
A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

B = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

# 1. Index wise multiplication
index_wise_multiplication = A*B

#2. matrix multiplication
matrix_multiplication = np.dot(A,B.T)# assuming you want to multiply A by the transpose of B

#3.Add both matrices
matrix_addition = A+B

#4. subtract matrix B from A
matrix_subtraction = A-B

#5. Divide matrix B by A
matrix_division = B/A

#Print the results

print("1. Index wise multiplication:")
print(index_wise_multiplication)

print("\n2. Matrix multiplication:")
print(matrix_multiplication)

print("\n3. Matrix addition:")
print(matrix_addition)

print("\n4. Matrix subtraction:")
print(matrix_subtraction)

print("\n5. Matrix division:")
print(matrix_division)

1. Index wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2. Matrix multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

3. Matrix addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4. Matrix subtraction:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5. Matrix division:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be used to swap the byte order of an array?

In [19]:
import numpy as np
# Create an array with some data

arr = np.array([1,256,65536],dtype = np.int32)

# swap the byte order
arr.byteswap(True)

print("Array with byte order swapped:")
print(arr)

Array with byte order swapped:
[16777216    65536      256]


13. What is the significance of the np.linalg.inv function?

Here are some key points regarding the significance of np.linalg.inv:

1.Solving Linear Equations: One of the primary uses of matrix inversion is in  solving systems of linear equations. Given a system of linear equations represented as Ax = b, where A is a coefficient matrix, x is the vector of unknowns, and b is the constant vector, the solution x can be obtained as x =A-1busing matrix inversion.

2.Determinant Calculation: The determinant of a matrix is a scalar value that represents various properties of the matrix. The determinant can be computed using matrix inversion as det (A)=1/det(A 1).

3.Eigenvalue and Eigenvector Calculation: In some cases, matrix inversion is used in the computation of eigenvalues and eigenvectors, which are crucial in various mathematical and scientific applications, including principal component analysis (PCA) and solving differential equations.

4.Pseudoinverse Calculation: In cases where the matrix is not square or not invertible, the pseudoinverse can be computed using methods like the Moore-Penrose pseudoinverse, which involves matrix inversion. The pseudoinverse is useful in solving least squares problems and in various other contexts.

5.Matrix Operations: Matrix inversion is a fundamental operation in linear algebra and is used in various matrix operations and transformations.

14. What does the np.reshape function do, and how is it used?

In [21]:
#The np.reshape function in NumPy is used to change the shape of an array without changing its data. It returns a new array with the specified shape while maintaining the same data. This function is particularly useful when you need to alter the dimensions of an array to match the requirements of a particular operation or algorithm.

#Here's how the np.reshape function works and how it is used:

#1.Syntax:
#numpy.reshape(a, newshape, order='C')

#>> a: The array to be reshaped.
#>> newshape: The new shape to which the array should be reshaped. It can be specified as a tuple of integers or as separate integer arguments. One of the dimensions can be set to -1, in which case it will be inferred from the length of the array and the remaining dimensions.
#>> order: Optional parameter specifying the order in which the elements should be read from the original array when constructing the reshaped array. It can be 'C' (row-major) or 'F' (column-major). The default is 'C'.

#2. Example:
import numpy as np
#original array
arr = np.array([1,2,3,4,5,6])

#Reshaped the array to a 2*3 matrix
reshaped_arr = np.reshape(arr,(2,3))

print("original array:")
print(arr)

print("\nReshaped array:")
print(reshaped_arr)


original array:
[1 2 3 4 5 6]

Reshaped array:
[[1 2 3]
 [4 5 6]]


15. What is broadcasting in Numpy?

In [22]:
#Broadcasting in NumPy is a powerful mechanism that allows arrays of different
 #shapes to be combined in arithmetic operations. When performing operations 
#involving arrays with different shapes, NumPy automatically "broadcasts" the 
#arrays to make their shapes compatible. This means that NumPy adjusts the 
#dimensions of the arrays to make them compatible for element-wise operations, 
#without the need for explicit looping over the arrays.

#The broadcasting rules in NumPy are as follows:

#Rule 1: If the arrays do not have the same number of dimensions, the shape of 
#the array with fewer dimensions is padded with ones on its leading (left) 
#side.

#Rule 2: If the shape of the arrays does not match in any dimension, the array 
#with shape equal to 1 in that dimension is stretched to match the shape of 
#the other array.

#Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an
 #error is raised.

#Broadcasting allows for more concise and readable code and eliminates the
 #need for explicit looping, resulting in more efficient computation. 
#It enables operations like adding a scalar to an array, adding arrays with 
#different shapes, and performing other element-wise operations on arrays of 
#different shapes.

#Here's a simple example to illustrate broadcasting:

import numpy as np

# Scalar broadcasting
arr1 = np.array([1, 2, 3])
scalar = 10
result1 = arr1 + scalar

# Array broadcasting
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr3 = np.array([10, 20, 30])
result2 = arr2 + arr3

print("Scalar Broadcasting:")
print(result1)

print("\nArray Broadcasting:")
print(result2)


Scalar Broadcasting:
[11 12 13]

Array Broadcasting:
[[11 22 33]
 [14 25 36]]
